backend:
  name: git-gateway

media_folder: "static/assets"
public_folder: "assets"

collections:
  # Styrktaraðilar | Top 5
  - name: "styrktaradilar_top5"
    label: "Styrktaraðilar Top 5"
    folder: "static/styrktaradilar_top5"
    create: true
    editor:
      preview: false
    fields:
      - { label: "Titill", name: "title", widget: "string" }
      - { label: "Lógó", name: "logo", widget: "image" }
      - { label: "Línkur", name: "sponsor_url", widget: "string" }
  # Styrktaraðilar | Rest
  - name: "styrktaradilar_rest"
    label: "Styrktaraðilar Rest"
    folder: "static/styrktaradilar_rest"
    create: true
    editor:
      preview: false
    fields:
      - { label: "Titill", name: "title", widget: "string" }
      - { label: "Lógó", name: "logo", widget: "image" }
      - { label: "Línkur", name: "sponsor_url", widget: "string" }
  # Hátíðin
  - name: "hatidin-undirsidur"
    label: "Hátíðin undirsíður"
    folder: "static/hatidin-undirsidur"
    create: true
    editor:
      preview: false
    fields:
      - { label: "Titill", name: "title", widget: "string" }
      - { label: "Titill Enska", name: "title-en", widget: "string" }
      - { label: "Mynd", name: "mynd", widget: "image" }
      - { label: "Video", name: "video", widget: "file", required: false }
      - { label: "Texti", name: "body", widget: "markdown" }
      - { label: "Order", name: "order", widget: "number" }
  # Aðilar
  - name: "Adilar"
    label: "Aðilar"
    folder: "static/adilar"
    create: true
    editor:
      preview: false
    fields:
      - { label: "Nafn", name: "title", widget: "string" }
      - { label: "Nafn Enska", name: "title-en", widget: "string" }
      - { label: "Mynd", name: "mynd", widget: "image" }
      - { label: "Texti", name: "body", widget: "markdown" }
      - { label: "Heimasíða", name: "heimasida", widget: "string" }
  # Gisting
  - name: "Gisting"
    label: "Gisting"
    folder: "static/gisting"
    create: true
    editor:
      preview: false
    fields:
      - { label: "Nafn", name: "title", widget: "string" }
      - { label: "Mynd", name: "mynd", widget: "image" }
      - { label: "Heimasíða", name: "heimasida", widget: "string" }
      - {
          label: "Google Maps url",
          name: "google-maps-url",
          widget: "string",
          required: false,
        }
      - label: "Staðsetning"
        name: "stadsetning"
        widget: "object"
        fields:
          - {
              label: "Bær",
              name: "baer",
              widget: "string",
              hint: "T.d. Patreksfjörður",
            }
          - {
              label: "Heimilisfang",
              name: "heimilisfang",
              widget: "string",
              hint: "T.d. Aðalstræti 31",
            }
          - { label: "Sími", name: "simi", widget: "string" }
