backend:
  name: git-gateway

media_folder: "static/assets"
public_folder: "assets"

# Hátíðin
collections:
  - name: "hatidin-undirsidur"
    label: "Hátíðin undirsíður"
    folder: "static/hatidin-undirsidur"
    create: true
    editor:
      preview: false
    fields:
      - { label: "Titill", name: "title", widget: "string" }
      - { label: "Mynd", name: "mynd", widget: "image" }
      - { label: "Texti", name: "body", widget: "markdown" }
