backend:
  name: git-gateway

media_folder: "static/assets"
public_folder: "assets"

collections:
  # Hátíðin
  - name: "hatidin-undirsidur"
    label: "Hátíðin undirsíður"
    folder: "static/hatidin-undirsidur"
    create: true
    editor:
      preview: false
    fields:
      - { label: "Titill", name: "title", widget: "string" }
      - { label: "Mynd", name: "mynd", widget: "image" }
      - { label: "Texti", name: "body", widget: "markdown" }
  # Gisting
  - name: "Gisting"
    label: "Gisting"
    folder: "static/gisting"
    create: true
    editor:
      preview: false
    fields:
      - { label: "Nafn", name: "nafn", widget: "string" }
      - { label: "Mynd", name: "mynd", widget: "string" }
      - {
          label: "Google Maps url",
          name: "google-maps-url",
          widget: "string",
          required: false,
        }
      - label: "Staðsetning"
        name: "stadsetning"
        widget: "object"
        fields:
          - {
              label: "Bær",
              name: "baer",
              widget: "string",
              hint: "T.d. Patreksfjörður",
            }
          - {
              label: "Heimilisfang",
              name: "heimilisfang",
              widget: "string",
              hint: "T.d. Aðalstræti 31",
            }
          - { label: "Sími", name: "simi", widget: "string" }
